global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: att-website-health
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://att-website:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: prometheus
    static_configs:
      - targets: 
          - localhost:9090